---
title: "Plotly Dashboard: Instacart Data"
output::flex_dashboard:
  orientation: columns
  vertical_layout: fill
---
## Setting up, loading libraries and data
```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)
library(flexdashboard)
```

```{r}
library(p8105.datasets)
data("instacart") 
```

## Filtering Instacart data only to include food, also taking a random sample of 10000 to decrease size and make this more feasible:
```{r}
instacart_filtered <- instacart |>
  mutate(department_id = as.integer(department_id)) |>
  filter(
    !is.na(department_id), 
    !department_id %in% c(17, 11, 18, 21)
  ) |>
  sample_n(size = 10000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart_filtered |> 
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box", colors = "viridis") |> 
  layout(
    title = "Distribution of Departments Shopped by Hour of Day",
    yaxis = list(title = "Hour of Day"),
    xaxis = list(title = "Department")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart_filtered |> 
  count(aisle) |> 
  mutate(aisle = fct_reorder(aisle, n)) |> 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis") |>
  layout(title = "Order Counts by Aisle")
```

### Chart C


